/**
 * 运行单元测试并生成 Markdown 测试报告（含数据日期）
 *
 * 用法：node test/run-tests.mjs
 * 输出：test/TEST_REPORT_<数据日期>.md
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync, existsSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const root = join(__dirname, '..');

// 数据日期：取 ilivedb.db 最近修改时间（mtime）作为"数据日期"
const dbPath = join(root, 'ilivedb.db');
let dataDate = '未知 / unknown';
if (existsSync(dbPath)) {
  const d = new Date(statSync(dbPath).mtime);
  dataDate = d.toISOString().slice(0, 10); // YYYY-MM-DD
}

const reportPath = join(__dirname, `TEST_REPORT_${dataDate}.md`);

// 运行测试，捕获 TAP 输出
let tap = '';
let exitCode = 0;
try {
  tap = execFileSync(process.execPath, ['--test', join(__dirname, 'js-to-sql.test.mjs')], {
    encoding: 'utf8',
    cwd: root,
  });
} catch (e) {
  tap = e.stdout || '';
  exitCode = e.status || 1;
}

// 解析 TAP，统计结果
const lines = tap.split('\n');
let total = 0, pass = 0, fail = 0, failLines = [];
for (const ln of lines) {
  // 兼容两种 TAP 摘要格式： "# tests 12" 与 "ℹ tests 12"
  const sum = ln.match(/(?:^#|^ℹ)\s+(tests|pass|fail|failed)\s+(\d+)/);
  if (sum) {
    const key = sum[1];
    const n = +sum[2];
    if (key === 'tests') total = n;
    else if (key === 'pass') pass = n;
    else if (key === 'fail' || key === 'failed') fail = n;
    continue;
  }
  // 统计每个用例（ok / not ok），作为兜底计数
  const ok = ln.match(/^(?:ok|not ok)\s+(\d+)\s+-\s+(.+)/);
  if (ok) {
    total++;
    if (ln.startsWith('ok')) pass++;
    else { fail++; failLines.push(`- ❌ ${ok[2]}`); }
  }
}

const now = new Date().toISOString();
const status = fail === 0 ? '✅ PASS（全部通过）' : '❌ FAIL（存在失败）';
const report = `# 单元测试报告 · JS-to-SQL Conversion

> 自动生成 · generated by \`test/run-tests.mjs\`

| 项目 | 值 |
|------|-----|
| **测试状态** | ${status} |
| **数据日期** | ${dataDate} |
| **生成时间** | ${now} |
| **用例总数** | ${total} |
| **通过** | ${pass} |
| **失败** | ${fail} |
| **被测目标** | \`js-to-sql.mjs\` |
| **测试案件** | \`test/fixtures/valid.js\`, \`no-country.js\`, \`special-chars.js\` |

## 覆盖点

- \`parseLocation\`：中英文 location 拆分、国家缺失自动补默认值
- \`sq\`：NULL 处理、单引号转义（\`'\` → \`''\`）
- \`extractObject\`：对象字面量提取
- \`generateSql\`：4 张表 INSERT 条数、国家补全、单引号转义、歌单 seq 顺序

${fail > 0 ? `## 失败明细\n${failLines.join('\n')}` : '## 失败明细\n无 · none'}

## 运行方式

\`\`\`bash
node test/run-tests.mjs        # 生成本报告
node --test test/js-to-sql.test.mjs   # 仅运行测试
\`\`\`
`;

writeFileSync(reportPath, report, 'utf8');
console.log(tap);
console.log(`\n📄 报告已写入 · report: ${reportPath}`);
console.log(`📅 数据日期 · data date: ${dataDate}`);
process.exit(exitCode);
