/**
 * 运行全部测试并生成报告 · Run the whole suite and write a report
 *
 * 用法 · usage:
 *   node test/run-tests.mjs
 *
 * 输出 · output:
 *   test/TEST_REPORT_<数据日期>.md   （文件名含数据日期 · filename carries the data date）
 *
 * 数据日期 · data date:
 *   取真实数据库 db/data.db 的最后修改日期（可用 DB_PATH 覆盖）；
 *   若文件不存在则回退为今天。
 *   Taken from the mtime of the real DB (db/data.db, overridable via DB_PATH);
 *   falls back to today when the file is missing.
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync, existsSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const ROOT = join(__dirname, '..');

/* ---------- 数据日期 · data date ---------- */
const dbFile = process.env.DB_PATH || join(ROOT, 'db', 'data.db');
const today = new Date().toISOString().slice(0, 10);
const dataDate = existsSync(dbFile)
  ? new Date(statSync(dbFile).mtime).toISOString().slice(0, 10)
  : today;

const reportPath = join(__dirname, `TEST_REPORT_${dataDate}.md`);

/* ---------- 运行测试 · run the suite ---------- */
let tap = '';
let exitCode = 0;
try {
  // 用 glob 显式匹配 *.test.mjs：既避免目录参数被当作模块入口，
  // 也避免误把 run-tests.mjs 自己当成测试文件执行。
  // A glob targeting *.test.mjs: passing a directory would be treated as a module entry,
  // and a bare pattern could pick up run-tests.mjs itself and recurse.
  tap = execFileSync(
    process.execPath,
    ['--test', '--test-reporter=tap', 'test/**/*.test.mjs'],
    { cwd: ROOT, encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 },
  );
} catch (e) {
  tap = `${e.stdout || ''}${e.stderr || ''}`;
  exitCode = e.status || 1;
}

/* ---------- 解析 TAP · parse the TAP output ---------- */
const lines = tap.split(/\r?\n/);
let total = 0;
let pass = 0;
let fail = 0;
const cases = [];
const failures = [];

for (const line of lines) {
  const summary = line.match(/^# (tests|pass|fail)\s+(\d+)/);
  if (summary) {
    if (summary[1] === 'tests') total = Number(summary[2]);
    else if (summary[1] === 'pass') pass = Number(summary[2]);
    else fail = Number(summary[2]);
    continue;
  }

  const item = line.match(/^\s*(not ok|ok)\s+\d+\s+-\s+(.+?)\s*$/);
  if (item) {
    const name = item[2];
    const ok = item[1] === 'ok';
    cases.push({ ok, name });
    if (!ok) failures.push(name);
  }
}

/* TAP 摘要缺失时以逐条结果兜底 · fall back to per-case results when the summary is absent */
if (total === 0 && cases.length > 0) {
  total = cases.length;
  pass = cases.filter((c) => c.ok).length;
  fail = total - pass;
}

const status = fail === 0 && total > 0 ? '✅ PASS（全部通过）' : '❌ FAIL（存在失败）';
const passRate = total > 0 ? ((pass / total) * 100).toFixed(1) : '0.0';

/* ---------- 生成报告 · build the report ---------- */
const caseTable = cases.length
  ? cases.map((c, i) => `| ${i + 1} | ${c.ok ? '✅' : '❌'} | ${c.name} |`).join('\n')
  : '| - | - | （未解析到用例） |';

const report = `# 单元测试报告 · iLive Admin CRUD

> 自动生成 · generated by \`test/run-tests.mjs\`

## 概要 · summary

| 项目 | 值 |
|------|-----|
| **测试状态** | ${status} |
| **数据日期** | ${dataDate} |
| **生成时间** | ${new Date().toISOString()} |
| **用例总数** | ${total} |
| **通过** | ${pass} |
| **失败** | ${fail} |
| **通过率** | ${passRate}% |
| **被测模块** | \`db.mjs\`、\`crud.mjs\`、\`server.mjs\` |
| **测试文件** | \`test/crud.test.mjs\`、\`test/api.test.mjs\` |
| **测试案例** | \`test/fixtures/*.json\` |
| **数据库文件** | \`${dbFile}\` |

## 覆盖范围 · coverage

- **db.mjs**：\`DB_PATH\` / \`SCHEMA_PATH\`、建表幂等、外键开启、单例
- **crud.mjs**：表配置与 schema 一致性、i18n JSON 校验与压缩、
  必填与类型校验、整型/布尔转换、外键与唯一约束的友好报错、
  单行表限制、分页与默认排序、全字段搜索 \`q\`、部分更新、级联删除统计
- **server.mjs**：页面与元信息接口、增删改查全链路、分页、
  全字段搜索 \`q\`、400 / 404 / 405 错误分支

## 失败明细 · failures

${failures.length ? failures.map((n) => `- ❌ ${n}`).join('\n') : '无 · none'}

## 用例清单 · test cases

| # | 结果 | 用例 |
|---|------|------|
${caseTable}

## 运行方式 · how to run

\`\`\`bash
node test/run-tests.mjs                  # 跑全部测试并生成本报告
node --test test/crud.test.mjs           # 仅数据层单元测试
node --test test/api.test.mjs            # 仅 REST API 集成测试
\`\`\`
`;

writeFileSync(reportPath, report, 'utf8');

console.log(tap);
console.log(`📄 报告已写入 · report: ${reportPath}`);
console.log(`📅 数据日期 · data date: ${dataDate}`);
console.log(`📊 结果 · result: ${pass}/${total} 通过，${fail} 失败`);

process.exit(exitCode);
